# 다중회귀2(모든 변수 포함)
water_bBac = lm(bBac ~ ., data = water_num)
water_bBod = lm(bBod ~ ., data = water_num)
water_bCod = lm(bCod ~ ., data = water_num)
water_bSs = lm(bSs ~ ., data = water_num)
water_bTn = lm(bTn ~ ., data = water_num)
water_bTp = lm(bTp ~ ., data = water_num)
water_bVal = lm(bVal ~ ., data = water_num)

summary(water_bBac)  
summary(water_bBod)
summary(water_bCod)
summary(water_bSs)
summary(water_bTn)
summary(water_bTp)
summary(water_bVal)