# 다중회귀3(온도,날씨,수온 제외)
water_bBac = lm(bBac ~ uBac + uBod + uCod + uSs + uTn + uTp + uVal, data = water_num)
water_bBod = lm(bBod ~ uBac + uBod + uCod + uSs + uTn + uTp + uVal, data = water_num)
water_bCod = lm(bCod ~ uBac + uBod + uCod + uSs + uTn + uTp + uVal, data = water_num)
water_bSs = lm(bSs ~ uBac + uBod + uCod + uSs + uTn + uTp + uVal, data = water_num)
water_bTn = lm(bTn ~ uBac + uBod + uCod + uSs + uTn + uTp + uVal, data = water_num)
water_bTp = lm(bTp ~ uBac + uBod + uCod + uSs + uTn + uTp + uVal, data = water_num)
water_bVal = lm(bVal ~ uBac + uBod + uCod + uSs + uTn + uTp + uVal, data = water_num)
summary(water_bBac)
summary(water_bBod)
summary(water_bCod)
summary(water_bSs)
summary(water_bTn)
summary(water_bTp)
summary(water_bVal)